function modify_attribute(net, varargin)
% Set paths
opts.prefix = 'v2';
opts.attribute = 'dtd';
opts = vl_argparse(opts, varargin);
opts.expDir = fullfile('data', opts.prefix, opts.attribute);
opts.attributeDir = fullfile('data', sprintf('%s-weights', opts.attribute));

% Create directories
mkdir(opts.expDir);
tmp = load(fullfile(opts.attributeDir, 'relu2_2.mat'));

classNames = tmp.classes;

imageName = 'Camouflage0011_S.png';
im = imread(fullfile('data', 'textures', imageName));
im = imresize(im, [224 224]);

for i = 1:length(classNames), 
    fprintf('class %i/%i: %s\n', i, length(classNames), classNames{i});
    outFile = fullfile(opts.expDir, sprintf('%s-%s.png', ...
                                            imageName(1:end-4), classNames{i}));
    if exist(outFile, 'file');
        continue;
    end
    res = texture_syn(im, net, ...
                      'imageSize', [224 224 3], ...
                      'TVbeta', 2, ...
                      'lambdaTV', 1e-6, ...
                      'beta', 2, ...
                      'lambdaLb', 0, ...
                      'contentLayer', {}, ...
                      'contentLayerWeights', [], ...
                      'textureLayer', {'relu1_1','relu2_1', 'relu3_1', 'relu4_1', 'relu5_1'}, ...
                      'textureLayerWeights', [1 1 1 1 1], ...
                      'attributeLayer', {'relu2_2', 'relu3_3', 'relu4_3', 'relu5_3'}, ...
                      'attributeLayerWeights', [1 1 1 1]*100, ...
                      'attributeTarget', classNames{i},...
                      'attributeDir', opts.attributeDir, ...
                      'maxIter', 250, ...
                      'useGPU', false);
    
    imwrite(gather(res.imsyn), outFile);
    if false,
        figure(1); clf;
        imshow(res.imsyn); axis image off;
        title(sprintf('inverse: %s', classNames{i}));
    end
end