% Demo for texture synthesis
% Setup directories
setup;

% Prepare image
%im = imread('data/textures/Camouflage0011_S.png');
im = imread('food.jpg');
im = imresize(im, [224 224]);

% Load network
if ~exist('net', 'var')
    net = load('data/models/imagenet-vgg-verydeep-16.mat');
end

% Run texture synthesis
tic;
res = texture_syn(im, net, ...
                  'imageSize', [224 224 3], ...
                  'TVbeta', 2, ...
                  'lambdaTV', 1e-6, ...
                  'beta', 2, ...
                  'lambdaLb', 0, ...
                  'contentLayer', {}, ...
                  'contentLayerWeights', [], ...
                  'textureLayer', {'relu1_1','relu2_1', 'relu3_1', 'relu4_1', 'relu5_1'}, ...
                  'textureLayerWeights', [1 1 1 1 1], ...
                  'attributeTarget', {}, ...
                  'attributeLayer', {}, ...
                  'attributeLayerWeights', [], ...
                  'textureInit', 'rand', ...
                  'maxIter', 500, ...
                  'useGPU', true);
toc;

% Display synthesized texture image
figure(1); clf;
subplot(1,3,1);imagesc(im); axis image off;
title('input');
subplot(1,3,2);imagesc(res.init); axis image off;
title('init');
subplot(1,3,3);imagesc(res.imsyn); axis image off;
title('synthesized'); set(gca, 'Color', [1 1 1]);
